[package]
name = "typeman"
version = "0.1.4"
edition = "2024"
readme = "README.md"
repository = "https://github.com/mzums/typeman"
license = "MIT"
keywords = ["typing", "type", "monkeytype", "typetest", "speed"]
categories = ["command-line-utilities", "games", "gui"]
description = "Typing speed test with practice mode in GUI, TUI and CLI"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
crossterm = "0.27.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.9.1"
macroquad = "0.4.14"
eframe = "0.31.1"
egui_plot = "0.32.1"
egui-macroquad = "0.17.3"
ratatui = "0.29.0"
